---

- name: configure jenkins slave with 3scale toolbox utility
  template:
    src: "{{ resources_home_dir }}/jenkins/3scale_toolbox_slave.yml"
    dest: "{{ work_dir }}/3scale_toolbox_slave.yml"
  changed_when: false
- k8s:
    state: present
    namespace: "{{ ocp_project }}"
    src: "{{ work_dir }}/3scale_toolbox_slave.yml"

- name: build and deploy jenkins
  template:
    src: "{{ resources_home_dir }}/jenkins/gpte-jenkins-persistent.yml"
    dest: "{{ work_dir }}/gpte-jenkins-persistent.yml"
  changed_when: false
- k8s:
    state: present
    namespace: "{{ ocp_project }}"
    src: "{{ work_dir }}/gpte-jenkins-persistent.yml"

- name: wait until jenkins is up and running
  shell: "{{ openshift_cli }} get dc {{ app_name }} -o template --template={{ json_template }} -n {{ ocp_project }}"
  vars:
    json_template: '\{\{.status.readyReplicas\}\}'
  register: result
  until: result.stdout == "1"
  retries: 20
  delay: 30
  changed_when: false

# Provide user with ability to create new jobs in Jenkins
- name: "provide {{ ocp_user }} with admin access to {{ ocp_project }}"
  shell: "{{ openshift_cli }} adm policy add-role-to-user admin {{ ocp_user }} -n {{ ocp_project }}"

# TO-DO: https://github.com/gpe-mw-training/rhte2019_E2E_API_Lifecycle_Mgmt_labs/issues/4
#
# oc policy add-role-to-user edit system:serviceaccount:openbanking-cicd:openbanking-jenkins -n openbanking-api-dev
# oc policy add-role-to-user edit system:serviceaccount:openbanking-cicd:openbanking-jenkins -n openbanking-api-test
# oc policy add-role-to-user edit system:serviceaccount:openbanking-cicd:openbanking-jenkins -n openbanking-api-prod


- name: delete project
  k8s:
    state: absent
    api_version: v1
    kind: Project
    name: "{{ ocp_project }}"
  tags: [ never, uninstall ]
