kind: List
apiVersion: v1
items:

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: custom-jenkins-build
  spec:
    source:                       
      git:
        uri: https://github.com/custom/repository
      type: Git
    strategy:                     
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: {{ JENKINS_IMAGE_STREAM_TAG }}
          namespace: {{ NAMESPACE }}
      type: Source
    output:                       
      to:
        kind: ImageStreamTag
        name: gpte-jenkins:1.0

- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      haproxy.router.openshift.io/timeout: 4m
      template.openshift.io/expose-uri: http://{.spec.host}{.spec.path}
    name: {{ JENKINS_SERVICE_NAME }}
  spec:
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: {{ JENKINS_SERVICE_NAME }}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: {{ JENKINS_SERVICE_NAME }}
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: {{ VOLUME_CAPACITY }}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
    name: {{ JENKINS_SERVICE_NAME }}
  spec:
    replicas: 1
    selector:
      name: {{ JENKINS_SERVICE_NAME }}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: {{ JENKINS_SERVICE_NAME }}
      spec:
        containers:
        - capabilities: {}
          env:
          - name: OPENSHIFT_ENABLE_OAUTH
            value: "{{ ENABLE_OAUTH }}"
          - name: OPENSHIFT_ENABLE_REDIRECT_PROMPT
            value: "true"
          - name: DISABLE_ADMINISTRATIVE_MONITORS
            value: "{{ DISABLE_ADMINISTRATIVE_MONITORS }}"
          - name: KUBERNETES_MASTER
            value: https://kubernetes.default:443
          - name: KUBERNETES_TRUST_CERTIFICATES
            value: "true"
          - name: JENKINS_SERVICE_NAME
            value: {{ JENKINS_SERVICE_NAME }}
          - name: JNLP_SERVICE_NAME
            value: {{ JNLP_SERVICE_NAME }}
          - name: ENABLE_FATAL_ERROR_LOG_FILE
            value: "{{ ENABLE_FATAL_ERROR_LOG_FILE }}"
          image: ' '
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 420
            periodSeconds: 360
            timeoutSeconds: 240
          name: jenkins
          readinessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 3
            timeoutSeconds: 240
          resources:
            limits:
              memory: {{ MEMORY_LIMIT }}

# GPTE: specify CPU limit so as to over-ride default from LimitRange
              cpu: 1

          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: '/var/lib/jenkins'
            name: {{ JENKINS_SERVICE_NAME }}-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        serviceAccountName: {{ JENKINS_SERVICE_NAME }}
        volumes:
        - name: {{ JENKINS_SERVICE_NAME }}-data
          persistentVolumeClaim:
            claimName: {{ JENKINS_SERVICE_NAME }}
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - jenkins
        from:
          kind: ImageStreamTag
          #name: {{ JENKINS_IMAGE_STREAM_TAG }}
          name: gpte-jenkins:1.0
          #namespace: {{ NAMESPACE }}
        lastTriggeredImage: ""
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      serviceaccounts.openshift.io/oauth-redirectreference.jenkins: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"{{ JENKINS_SERVICE_NAME }}"}}'
    name: {{ JENKINS_SERVICE_NAME }}
- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    name: {{ JENKINS_SERVICE_NAME }}_edit
  roleRef:
    name: edit
  subjects:
  - kind: ServiceAccount
    name: {{ JENKINS_SERVICE_NAME }}
- apiVersion: v1
  kind: Service
  metadata:
    name: {{ JNLP_SERVICE_NAME }}
  spec:
    ports:
    - name: agent
      nodePort: 0
      port: 50000
      protocol: TCP
      targetPort: 50000
    selector:
      name: {{ JENKINS_SERVICE_NAME }}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      service.alpha.openshift.io/dependencies: '[{"name": "{{ JNLP_SERVICE_NAME }}", "namespace": "", "kind": "Service"}]'
      service.openshift.io/infrastructure: "true"
    name: {{ JENKINS_SERVICE_NAME }}
  spec:
    ports:
    - name: web
      nodePort: 0
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      name: {{ JENKINS_SERVICE_NAME }}
    sessionAffinity: None
    type: ClusterIP
