apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: openbanking-publish-api-pipeline
metadata:
  annotations:
    description: 3scale API publishing Pipeline
  name: openbanking-publish-api-pipeline
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      name: openbanking-publish-api-pipeline
    name: openbanking-publish-api-pipeline
  spec:
    output: null
    postCommit: null
    resources: null
    runPolicy: Serial
    source:
      type: None
    source:
      git:
        uri: ${GIT_REPO}
        ref: ${GIT_BRANCH}
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: cicd-3scale/openbanking-api/Jenkinsfile
        env:
        - name: GIT_BRANCH
          value: ${GIT_BRANCH}
        - name: GIT_REPO
          value: ${GIT_REPO}
        - name: DEV_PRIVATE_BASE_URL
          value: ${DEV_PRIVATE_BASE_URL}
        - name: PROD_PRIVATE_BASE_URL
          value: ${PROD_PRIVATE_BASE_URL}
        - name: DEV_PRODUCTION_PUBLIC_BASE_URL
          value: ${DEV_PRODUCTION_PUBLIC_BASE_URL}
        - name: DEV_STAGING_PUBLIC_BASE_URL
          value: ${DEV_STAGING_PUBLIC_BASE_URL}
        - name: PROD_PRODUCTION_PUBLIC_BASE_URL
          value: ${PROD_PRODUCTION_PUBLIC_BASE_URL}
        - name: PROD_STAGING_PUBLIC_BASE_URL
          value: ${PROD_STAGING_PUBLIC_BASE_URL}
        - name: API_BASE_SYSTEM_NAME
          value: ${API_BASE_SYSTEM_NAME}
        - name: DEV_PROJECT
          value: ${DEV_PROJECT}
        - name: TEST_PROJECT
          value: ${TEST_PROJECT}
        - name: PROD_PROJECT
          value: ${PROD_PROJECT}
        - name: IMAGE_NAMESPACE
          value: ${IMAGE_NAMESPACE}
        - name: SECRET_NAME
          value: ${SECRET_NAME}
        - name: TARGET_INSTANCE_DEV
          value: ${TARGET_INSTANCE_DEV}
        - name: TARGET_INSTANCE_PROD
          value: ${TARGET_INSTANCE_PROD}
        - name: DEV_DEVELOPER_ACCOUNT_ID
          value: ${DEV_DEVELOPER_ACCOUNT_ID}
        - name: PROD_DEVELOPER_ACCOUNT_ID
          value: ${PROD_DEVELOPER_ACCOUNT_ID}
        - name: DISABLE_TLS_VALIDATION
          value: ${DISABLE_TLS_VALIDATION}
        - name: APPLICATION_NAME
          value: ${APPLICATION_NAME}
        - name: OPENAPI_SPECIFICATION_FILE
          value: ${OPENAPI_SPECIFICATION_FILE}
        - name: TOOLBOX_IMAGE_REGISTRY
          value: ${TOOLBOX_IMAGE_REGISTRY}
parameters:
- name: GIT_REPO
  value: https://github.com/gpe-mw-training/rhte2019_E2E_API_Lifecycle_Mgmt_labs.git
  required: true
- name: GIT_BRANCH
  value: master
  required: true
- name: DEV_PRIVATE_BASE_URL
  required: true
- name: PROD_PRIVATE_BASE_URL
  required: true
- name: DEV_PRODUCTION_PUBLIC_BASE_URL
  #required: true
- name: DEV_STAGING_PUBLIC_BASE_URL
  #required: true
- name: PROD_PRODUCTION_PUBLIC_BASE_URL
  #required: true
- name: PROD_STAGING_PUBLIC_BASE_URL
  #required: true
- name: API_BASE_SYSTEM_NAME
  value: 3scale-mt-api0
  required: true
- name: DEV_PROJECT
  required: true
  value: openbanking-api-dev
- name: TEST_PROJECT
  required: true
  value: openbanking-api-test
- name: PROD_PROJECT
  required: true
  value: openbanking-api-prod
- name: IMAGE_NAMESPACE
  required: true
  value: openbanking-cicd
- name: SECRET_NAME
  value: 3scale-toolbox
  required: true  
- name: TARGET_INSTANCE_DEV
  value: openbanking-dev
  required: true  
- name: TARGET_INSTANCE_PROD
  value: openbanking-prod
  required: true
- name: DEV_DEVELOPER_ACCOUNT_ID
  required: true
  value: "5"
- name: PROD_DEVELOPER_ACCOUNT_ID
  required: true
  value: "7"
- name: DISABLE_TLS_VALIDATION
  value: "yes"
- name: APPLICATION_NAME
  value: "openbanking-api"
  required: true
- name: OPENAPI_SPECIFICATION_FILE
  required: true
- name: TOOLBOX_IMAGE_REGISTRY
  required: true
  value: "quay.io/redhat/3scale-toolbox:v0.12.3"






















