apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: pipeline-publish-api-3scale
metadata:
  annotations:
    description: 3scale API publishing Pipeline
  name: publish-api-3scale
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      name: publish-api-3scale
    name: publish-api-3scale
  spec:
    output: null
    postCommit: null
    resources: null
    runPolicy: Serial
    source:
      type: None
    source:
      git:
        uri: ${GIT_REPO}
        ref: ${GIT_BRANCH}
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: cicd-3scale/3scaletoolbox/Jenkinsfile
        env:
        - name: GIT_BRANCH
          value: ${GIT_BRANCH}
        - name: GIT_REPO
          value: ${GIT_REPO}
        - name: PRIVATE_BASE_URL
          value: ${PRIVATE_BASE_URL}
        - name: PUBLIC_PRODUCTION_WILDCARD_DOMAIN
          value: ${PUBLIC_PRODUCTION_WILDCARD_DOMAIN}
        - name: PUBLIC_STAGING_WILDCARD_DOMAIN
          value: ${PUBLIC_STAGING_WILDCARD_DOMAIN}
        - name: PRODUCTION_PUBLIC_BASE_URL
          value: ${PRODUCTION_PUBLIC_BASE_URL}
        - name: STAGING_PUBLIC_BASE_URL
          value: ${STAGING_PUBLIC_BASE_URL}
        - name: API_BASE_SYSTEM_NAME
          value: ${API_BASE_SYSTEM_NAME}
        - name: DEV_PROJECT
          value: ${DEV_PROJECT}
        - name: TEST_PROJECT
          value: ${TEST_PROJECT}
        - name: PROD_PROJECT
          value: ${PROD_PROJECT}
        - name: IMAGE_NAMESPACE
          value: ${IMAGE_NAMESPACE}
        - name: SECRET_NAME
          value: ${SECRET_NAME}
        - name: TARGET_INSTANCE
          value: ${TARGET_INSTANCE}
        - name: DEVELOPER_ACCOUNT_ID
          value: ${DEVELOPER_ACCOUNT_ID}
        - name: DISABLE_TLS_VALIDATION
          value: ${DISABLE_TLS_VALIDATION}
        - name: PLAN_YAML_FILE_PATH
          value: ${PLAN_YAML_FILE_PATH}
        - name: TOOLBOX_IMAGE_REGISTRY
          value: ${TOOLBOX_IMAGE_REGISTRY}

          

parameters:
- name: GIT_REPO
  value: https://github.com/gpe-mw-training/rhte2019_E2E_API_Lifecycle_Mgmt_labs.git
  required: true
- name: GIT_BRANCH
  value: master
  required: true
- name: PRIVATE_BASE_URL
  value: http://gateway-service.openbanking-api-dev.svc.cluster.local:8080
  required: true
- name: PUBLIC_PRODUCTION_WILDCARD_DOMAIN
  value: prod.apps-52ec.generic.opentlc.com
- name: PUBLIC_STAGING_WILDCARD_DOMAIN
  value: staging.apps-52ec.generic.opentlc.com
- name: PRODUCTION_PUBLIC_BASE_URL
  value: https://openbanking-api-prod.apps-52ec.generic.opentlc.com
  #required: true
- name: STAGING_PUBLIC_BASE_URL
  value: https://openbanking-api-staging.apps-52ec.generic.opentlc.com
  #required: true
- name: API_BASE_SYSTEM_NAME
  value: 3scale-mt-api0
  required: true
- name: DEV_PROJECT
  required: true
- name: TEST_PROJECT
  required: true
- name: PROD_PROJECT
  required: true
- name: IMAGE_NAMESPACE
  required: true
- name: SECRET_NAME
  value: 3scale-toolbox
  required: true  
- name: TARGET_INSTANCE
  value: instance_a
  required: true  
- name: DEVELOPER_ACCOUNT_ID
  required: true
- name: DISABLE_TLS_VALIDATION
  value: "yes"
- name: PLAN_YAML_FILE_PATH
  value: https://github.com/gpe-mw-training/rhte2019_E2E_API_Lifecycle_Mgmt_labs/master/cicd-3scale/3scaletoolbox/plan.yaml
- name: TOOLBOX_IMAGE_REGISTRY
  value: quay.io/satyaj/3scale-toolbox-container:1.2-2























