---

dependencies:
  - role: work_dir
    vars:
      work_dir_name: "{{ app_name }}"
  - role: openshift_project
    vars:
      ocp_project: "{{ base_name }}-nexus"
      is_control_plane: true
    when: >
      ACTION is not defined or
      ACTION is none or
      ACTION|trim() == "" or
      ACTION|trim() == "install"


# Determine OCP route wildcard domain so as to pass to Nexus provisioning
  - role: openshift_domain
    when: >
      ACTION is not defined or
      ACTION is none or
      ACTION|trim() == "" or
      ACTION|trim() == "install"
